import { buildPipeline } from './agents/agent';
import { InMemorySessionService, Event, EventActions } from '@iqai/adk';
import { env } from './env';
import { retryWithBackoff, parseRetryDelay } from './utils/rate-limiter';
import * as fs from 'fs';
import * as path from 'path';
import MarkdownIt from 'markdown-it';
import * as puppeteer from 'puppeteer';

interface AnalysisResult {
  timestamp: string;
  query: string;
  agents: {
    research: string;
    analysis: string;
    pipeline: string;
  };
  results: {
    research: {
      data: any;
      preview: string;
    };
    analysis: {
      data: any;
      preview: string;
    };
  };
  validation?: {
    score: number;
    isValid: boolean;
    errors: string[];
    warnings: string[];
    extractedTokens: string[];
  };
  status: 'completed' | 'failed' | 'completed-with-issues';
  duration?: number;
  market_snapshot?: string;
}

const log = (...args: any[]) => {
  if (env.ADK_DEBUG) console.log(...args);
};

const saveToMarkdown = async (content: string, filename: string) => {
  const outputDir = path.join(process.cwd(), 'output');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  const filePath = path.join(outputDir, `${filename}.md`);
  fs.writeFileSync(filePath, content);
  console.log(`📄 Markdown saved to: ${filePath}`);
  return filePath;
};

const renderMarkdownToPdf = async (markdownContent: string, filename: string) => {
  try {
    const md = new MarkdownIt();
    const htmlContent = md.render(markdownContent);
    
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    
    const fullHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          h1 { color: #333; }
          h2 { color: #555; }
          pre { background: #f4f4f4; padding: 15px; border-radius: 5px; }
          code { background: #f4f4f4; padding: 2px 5px; border-radius: 3px; }
        </style>
      </head>
      <body>${htmlContent}</body>
      </html>
    `;
    
    await page.setContent(fullHtml);
    
    const outputDir = path.join(process.cwd(), 'output');
    const pdfPath = path.join(outputDir, `${filename}.pdf`);
    
    await page.pdf({ 
      path: pdfPath, 
      format: 'A4',
      printBackground: true 
    });
    
    await browser.close();
    console.log(`📊 PDF saved to: ${pdfPath}`);
    return pdfPath;
  } catch (error) {
    console.error('❌ Failed to generate PDF:', error);
    return null;
  }
};

const generateMarkdownReport = (analysisResult: AnalysisResult): string => {
  const summary = analysisResult.results.analysis.preview || '';
  const full = analysisResult.results.analysis.data;

  let fullSection = '';
  if (full === null || typeof full === 'undefined') {
    fullSection = 'No detailed analysis available.';
  } else if (typeof full === 'string') {
    const unescaped = full.replace(/\\n/g, '\n');
    fullSection = '```md\n' + unescaped + '\n```';
  } else {
    fullSection = '```json\n' + JSON.stringify(full, null, 2) + '\n```';
  }

  return [
    '# Final Cryptocurrency Analysis',
    '',
    '## Query',
    analysisResult.query,
    '',
    '## Final Analysis (Summary)',
    summary,
    '',
    '## Final Analysis (Full)',
    fullSection,
    '',
    '*Report generated by Crypto Analysis Pipeline*'
  ].join('\n');
};

async function main() {
  const startTime = Date.now();

  try {
    console.log('Starting cryptocurrency analysis application...');

    const { tokenMarket, webSearch, marketData, contentScraping, analysis } = 
      await buildPipeline({ 
        tokenMarket: env.LLM_MODEL,
        webSearch: env.QUERY_LLM_MODEL,
        marketData: 'gemini-1.5-flash-8b',
        contentScraping: 'gemini-2.0-flash',
        analysis: env.LLM_MODEL
      });

    const testQuery = env.USER_QUERY;
    console.log(`Running query: "${testQuery}"`);

    const sessionService = new InMemorySessionService();
    const session = await sessionService.createSession('crypto-analysis-app', 'user-default', {
      original_query: testQuery,
      current_step: 'init'
    });

    const appendState = async (author: string, delta: Record<string, any>, message: string) => {
      const event = new Event({ 
        author, 
        content: { parts: [{ text: message }] }, 
        actions: new EventActions({ stateDelta: delta }), 
        timestamp: Math.floor(Date.now() / 1000) 
      });
      await sessionService.appendEvent(session, event);
    };

    const extractTopFindings = (text: string): string => {
      const lines = text.split('\n');
      let findingsText = '';
      let inFindingsSection = false;
      for (const line of lines) {
        if (line.match(/Top Findings|Findings/i)) {
          inFindingsSection = true;
          continue;
        }
        if (inFindingsSection && line.includes('###') && !line.includes('Finding')) break;
        if (inFindingsSection && line.trim()) findingsText += line + '\n';
      }
      return findingsText.trim() || 'Analysis findings extracted from web search results.';
    };

    const wait = (ms: number) => new Promise(res => setTimeout(res, ms));
    const delayMs = 0;

    console.log('\n🚀 Running sequential agent pipeline manually...');
    let pipelineResult = '';
    let stepResults: any[] = [];

    try {
      const runStep = async (label: string, fn: () => Promise<any>) => {
        console.log(`   Step: ${label}...`);
        const res = await retryWithBackoff(fn, label, env.MAX_RETRIES || 3);
        stepResults.push({ step: label, result: res });
        console.log(`   ✅ ${label} complete`);
        if (delayMs > 0) await wait(delayMs);
        return res;
      };

      const step1 = await runStep('tokenMarket', () => tokenMarket.runner.ask(testQuery));
      const step2 = await runStep('webSearch', () => webSearch.runner.ask(`User Query: ${testQuery}\nToken Market Data: ${step1}`));
      const step3 = await runStep('marketData', () => marketData.runner.ask(`User Query: ${testQuery}\nToken Market Data: ${step1}\nWeb Search Results: ${step2}`));
      const step4 = await runStep('contentScraping', () => contentScraping.runner.ask(`User Query: ${testQuery}\nWeb Search Results: ${step2}\nMarket Data: ${step3}`));
      const step5 = await runStep('analysis', () => analysis.runner.ask(`User Query: ${testQuery}\nResearch Data: ${step2}\nMarket Data: ${step3}\nContent: ${step4}`));

      pipelineResult = JSON.stringify({
        query: testQuery,
        steps: stepResults,
        finalAnalysis: step5,
        executionFlow: 'sequential_manual'
      });
      
      console.log('✅ Sequential pipeline completed successfully');

      await appendState('sequential_pipeline_manual', {
        current_step: 'pipeline_complete',
        step_results: stepResults,
        final_analysis: step5,
        pipeline_raw: pipelineResult
      }, 'Sequential pipeline execution completed');

    } catch (error: any) {
      console.error('❌ Pipeline failed:', error?.message);

      if (error?.status === 503 || String(error?.message || '').toLowerCase().includes('unavailable')) {
        console.log('⚠️ Service unavailable. Try again later.');
      }
      if (error?.message?.includes("quota") || error?.status === 429) {
        console.log(`⏰ Quota exceeded. Wait ${parseRetryDelay(error) / 1000}s`);
      }

      pipelineResult = JSON.stringify({
        error: `Pipeline failure: ${error?.message ?? JSON.stringify(error)}`,
        completedSteps: stepResults,
        executionFlow: 'sequential_manual_failed'
      });

      await appendState('system', { 
        pipeline_error: error?.message, 
        current_step: 'pipeline_failed',
        completed_steps: stepResults.length
      }, 'Pipeline failed');
    }

    const analysisResult: AnalysisResult = {
      timestamp: new Date().toISOString(),
      query: testQuery,
      agents: {
        research: env.QUERY_LLM_MODEL,
        analysis: env.LLM_MODEL,
        pipeline: 'sequential_manual'
      },
      results: {
        research: {
          data: pipelineResult,
          preview: extractTopFindings(stepResults.find(s => s.step === 'webSearch')?.result || '')
        },
        analysis: {
          data: stepResults.find(s => s.step === 'analysis')?.result || '',
          preview: extractTopFindings(stepResults.find(s => s.step === 'analysis')?.result || '')
        }
      },
      status: 'completed',
      duration: Date.now() - startTime
    };

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `crypto-analysis-${timestamp}`;
    
    const markdownReport = generateMarkdownReport(analysisResult);
    const mdPath = await saveToMarkdown(markdownReport, filename);
    await renderMarkdownToPdf(markdownReport, filename);

    console.log('\n🎉 Sequential workflow completed successfully!');

  } catch (err) {
    console.error('❌ Application failed:', err);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}